name: mini_tools
description: A pure dart tool class, including file tools, sp tools, etc.
version: 3.0.2
homepage: https://github.com/flutterme/mini_tools.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  synchronized: ^3.0.0
  flutter_image_compress: ^2.3.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  rational: ^2.2.3
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
